services:
  ratings:
    build: ./ratings
    image: ghcr.io/pspapleng/bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME

  mongodb:
    image: bitnami/mongodb:5.0.2-debian-10-r2
    # ports:
    #   - "27017:27017"
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: CHANGEME
      MONGODB_DATABASE: ratings
  
  details:
    build: ./details
    image: ghcr.io/pspapleng/bookinfo-details:dev
    ports:
      - "8081:9080"

  reviews:
    build: ./reviews
    image: ghcr.io/pspapleng/bookinfo-reviews:dev
    ports:
      - "8082:9080"
    environment:
      RATINGS_SERVICE: http://ratings:8080
      ENABLE_RATINGS: 'true'
  
  productpage:
    build: ./productpage
    image: ghcr.io/pspapleng/bookinfo-productpage:dev
    ports:
      - "8083:9080"
    environment:
      RATINGS_HOSTNAME: http://ratings:8080
      DETAILS_HOSTNAME: http://details:9080
      REVIEWS_HOSTNAME: http://reviews:9080